### Record the efforts for a given day
POST http://localhost:8080/v0/efforts/2020-11-07?hours=7

### Clear recorded efforts
DELETE http://localhost:8080/v0/efforts


### Retrieve the amount to invoice for a given day
GET http://localhost:8080/v1/invoices/2020-11-07

### Retrieve the amount to invoice for a given day, with arrow option
GET http://localhost:8080/v2/invoices/2020-11-07
